name: ElianAI
options:
  bundleIdPrefix: com.synquox
packages:
  GenerativeAI:
    url: https://github.com/google/generative-ai-swift
    exactVersion: 0.5.6
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.4.0
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup
    from: 2.7.0
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: 2.5.1
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation
    from: 0.9.0
targets:
  ElianAI:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ElianAI
        excludes:
          - "**/*.plist"
    settings:
      base:
        SWIFT_VERSION: "5.10"
        PRODUCT_BUNDLE_IDENTIFIER: com.synquox.ElianAI
    dependencies:
      - package: GenerativeAI
        product: GoogleGenerativeAI
      - package: MarkdownUI
      - package: SwiftSoup
      - package: Supabase
      - package: ZIPFoundation
    info:
      path: ElianAI/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSupportsMultipleScenes: true
